"""add daily missions column

Revision ID: 376f0d1c0038
Revises: 49fbff39bd98
Create Date: 2026-03-30 09:47:38.933714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376f0d1c0038'
down_revision: Union[str, None] = '49fbff39bd98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('daily_missions', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'daily_missions')
    # ### end Alembic commands ###